package com.jrs.www.po;

public class JrsAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_admin.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_admin.admin_name
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_admin.admin_sex
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer adminSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_admin.admin_username
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String adminUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_admin.admin_password
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String adminPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_admin.admin_salt
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String adminSalt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_admin.id
     *
     * @return the value of jrs_admin.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_admin.id
     *
     * @param id the value for jrs_admin.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_admin.admin_name
     *
     * @return the value of jrs_admin.admin_name
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_admin.admin_name
     *
     * @param adminName the value for jrs_admin.admin_name
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_admin.admin_sex
     *
     * @return the value of jrs_admin.admin_sex
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getAdminSex() {
        return adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_admin.admin_sex
     *
     * @param adminSex the value for jrs_admin.admin_sex
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setAdminSex(Integer adminSex) {
        this.adminSex = adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_admin.admin_username
     *
     * @return the value of jrs_admin.admin_username
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getAdminUsername() {
        return adminUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_admin.admin_username
     *
     * @param adminUsername the value for jrs_admin.admin_username
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_admin.admin_password
     *
     * @return the value of jrs_admin.admin_password
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_admin.admin_password
     *
     * @param adminPassword the value for jrs_admin.admin_password
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_admin.admin_salt
     *
     * @return the value of jrs_admin.admin_salt
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getAdminSalt() {
        return adminSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_admin.admin_salt
     *
     * @param adminSalt the value for jrs_admin.admin_salt
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setAdminSalt(String adminSalt) {
        this.adminSalt = adminSalt;
    }
}