package com.jrs.www.po;

import java.util.Date;

public class JrsChannel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.channel_name
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.play_type_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer playTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.视频流类型
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String videoStreamType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.播放地址
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String 播放地址;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer modifiyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_channel.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date modifiyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.id
     *
     * @return the value of jrs_channel.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.id
     *
     * @param id the value for jrs_channel.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.channel_name
     *
     * @return the value of jrs_channel.channel_name
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.channel_name
     *
     * @param channelName the value for jrs_channel.channel_name
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.play_type_id
     *
     * @return the value of jrs_channel.play_type_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getPlayTypeId() {
        return playTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.play_type_id
     *
     * @param playTypeId the value for jrs_channel.play_type_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setPlayTypeId(Integer playTypeId) {
        this.playTypeId = playTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.视频流类型
     *
     * @return the value of jrs_channel.视频流类型
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getVideoStreamType() {
        return videoStreamType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.视频流类型
     *
     * @param 视频流类型 the value for jrs_channel.视频流类型
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setVideoStreamType(String videoStreamType) {
        this.videoStreamType = videoStreamType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.播放地址
     *
     * @return the value of jrs_channel.播放地址
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String get播放地址() {
        return 播放地址;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.播放地址
     *
     * @param 播放地址 the value for jrs_channel.播放地址
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void set播放地址(String 播放地址) {
        this.播放地址 = 播放地址;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.delete_status
     *
     * @return the value of jrs_channel.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.delete_status
     *
     * @param deleteStatus the value for jrs_channel.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.create_user_id
     *
     * @return the value of jrs_channel.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.create_user_id
     *
     * @param createUserId the value for jrs_channel.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.create_time
     *
     * @return the value of jrs_channel.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.create_time
     *
     * @param createTime the value for jrs_channel.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.modifiy_user_id
     *
     * @return the value of jrs_channel.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getModifiyUserId() {
        return modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.modifiy_user_id
     *
     * @param modifiyUserId the value for jrs_channel.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setModifiyUserId(Integer modifiyUserId) {
        this.modifiyUserId = modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_channel.modifiy_time
     *
     * @return the value of jrs_channel.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getModifiyTime() {
        return modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_channel.modifiy_time
     *
     * @param modifiyTime the value for jrs_channel.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setModifiyTime(Date modifiyTime) {
        this.modifiyTime = modifiyTime;
    }
}
