package com.jrs.www.po;

import java.util.Date;

public class JrsMobileAdv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.adv_position_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer advPositionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.mobile_sys_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer mobileSysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.jump_url
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String jumpUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.delete_status
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.create_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.create_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.modifiy_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer modifiyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.modifiy_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Date modifiyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv.adv_content
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String advContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.id
     *
     * @return the value of jrs_mobile_adv.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.id
     *
     * @param id the value for jrs_mobile_adv.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.adv_position_id
     *
     * @return the value of jrs_mobile_adv.adv_position_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getAdvPositionId() {
        return advPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.adv_position_id
     *
     * @param advPositionId the value for jrs_mobile_adv.adv_position_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setAdvPositionId(Integer advPositionId) {
        this.advPositionId = advPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.mobile_sys_id
     *
     * @return the value of jrs_mobile_adv.mobile_sys_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getMobileSysId() {
        return mobileSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.mobile_sys_id
     *
     * @param mobileSysId the value for jrs_mobile_adv.mobile_sys_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setMobileSysId(Integer mobileSysId) {
        this.mobileSysId = mobileSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.jump_url
     *
     * @return the value of jrs_mobile_adv.jump_url
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getJumpUrl() {
        return jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.jump_url
     *
     * @param jumpUrl the value for jrs_mobile_adv.jump_url
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.delete_status
     *
     * @return the value of jrs_mobile_adv.delete_status
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.delete_status
     *
     * @param deleteStatus the value for jrs_mobile_adv.delete_status
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.create_user_id
     *
     * @return the value of jrs_mobile_adv.create_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.create_user_id
     *
     * @param createUserId the value for jrs_mobile_adv.create_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.create_time
     *
     * @return the value of jrs_mobile_adv.create_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.create_time
     *
     * @param createTime the value for jrs_mobile_adv.create_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.modifiy_user_id
     *
     * @return the value of jrs_mobile_adv.modifiy_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getModifiyUserId() {
        return modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.modifiy_user_id
     *
     * @param modifiyUserId the value for jrs_mobile_adv.modifiy_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setModifiyUserId(Integer modifiyUserId) {
        this.modifiyUserId = modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.modifiy_time
     *
     * @return the value of jrs_mobile_adv.modifiy_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Date getModifiyTime() {
        return modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.modifiy_time
     *
     * @param modifiyTime the value for jrs_mobile_adv.modifiy_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setModifiyTime(Date modifiyTime) {
        this.modifiyTime = modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv.adv_content
     *
     * @return the value of jrs_mobile_adv.adv_content
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getAdvContent() {
        return advContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv.adv_content
     *
     * @param advContent the value for jrs_mobile_adv.adv_content
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setAdvContent(String advContent) {
        this.advContent = advContent;
    }
}