package com.jrs.www.po;

import java.util.Date;

public class JrsMatchType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_type.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_type.type_name
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_type.delete_status
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_type.create_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_type.create_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_type.modifiy_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer modifiyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_type.modifiy_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Date modifiyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_type.id
     *
     * @return the value of jrs_match_type.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_type.id
     *
     * @param id the value for jrs_match_type.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_type.type_name
     *
     * @return the value of jrs_match_type.type_name
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_type.type_name
     *
     * @param typeName the value for jrs_match_type.type_name
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_type.delete_status
     *
     * @return the value of jrs_match_type.delete_status
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_type.delete_status
     *
     * @param deleteStatus the value for jrs_match_type.delete_status
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_type.create_user_id
     *
     * @return the value of jrs_match_type.create_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_type.create_user_id
     *
     * @param createUserId the value for jrs_match_type.create_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_type.create_time
     *
     * @return the value of jrs_match_type.create_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_type.create_time
     *
     * @param createTime the value for jrs_match_type.create_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_type.modifiy_user_id
     *
     * @return the value of jrs_match_type.modifiy_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getModifiyUserId() {
        return modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_type.modifiy_user_id
     *
     * @param modifiyUserId the value for jrs_match_type.modifiy_user_id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setModifiyUserId(Integer modifiyUserId) {
        this.modifiyUserId = modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_type.modifiy_time
     *
     * @return the value of jrs_match_type.modifiy_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Date getModifiyTime() {
        return modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_type.modifiy_time
     *
     * @param modifiyTime the value for jrs_match_type.modifiy_time
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setModifiyTime(Date modifiyTime) {
        this.modifiyTime = modifiyTime;
    }
}