package com.jrs.www.po;

public class JrsMobileSys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_sys.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_sys.mobile_sys
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String mobileSys;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_sys.id
     *
     * @return the value of jrs_mobile_sys.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_sys.id
     *
     * @param id the value for jrs_mobile_sys.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_sys.mobile_sys
     *
     * @return the value of jrs_mobile_sys.mobile_sys
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getMobileSys() {
        return mobileSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_sys.mobile_sys
     *
     * @param mobileSys the value for jrs_mobile_sys.mobile_sys
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setMobileSys(String mobileSys) {
        this.mobileSys = mobileSys;
    }
}