package com.jrs.www.po;

import java.util.Date;

public class JrsMatchVideotape {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.id
     *
     * @mbg.generated Mon Jun 04 17:56:26 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.match_type_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer matchTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.match_type
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String matchType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.league_match_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer leagueMatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.league_match
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String leagueMatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.home_team_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer homeTeamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.home_team
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String homeTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.home_team_log
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String homeTeamLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.off_team_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer offTeamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.off_team
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String offTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.off_team_log
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String offTeamLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.score
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.match_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String matchTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer modifiyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_match_videotape.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date modifiyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.id
     *
     * @return the value of jrs_match_videotape.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.id
     *
     * @param id the value for jrs_match_videotape.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.match_type_id
     *
     * @return the value of jrs_match_videotape.match_type_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getMatchTypeId() {
        return matchTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.match_type_id
     *
     * @param matchTypeId the value for jrs_match_videotape.match_type_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setMatchTypeId(Integer matchTypeId) {
        this.matchTypeId = matchTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.match_type
     *
     * @return the value of jrs_match_videotape.match_type
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.match_type
     *
     * @param matchType the value for jrs_match_videotape.match_type
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setMatchType(String matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.league_match_id
     *
     * @return the value of jrs_match_videotape.league_match_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getLeagueMatchId() {
        return leagueMatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.league_match_id
     *
     * @param leagueMatchId the value for jrs_match_videotape.league_match_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setLeagueMatchId(Integer leagueMatchId) {
        this.leagueMatchId = leagueMatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.league_match
     *
     * @return the value of jrs_match_videotape.league_match
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getLeagueMatch() {
        return leagueMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.league_match
     *
     * @param leagueMatch the value for jrs_match_videotape.league_match
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setLeagueMatch(String leagueMatch) {
        this.leagueMatch = leagueMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.home_team_id
     *
     * @return the value of jrs_match_videotape.home_team_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getHomeTeamId() {
        return homeTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.home_team_id
     *
     * @param homeTeamId the value for jrs_match_videotape.home_team_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setHomeTeamId(Integer homeTeamId) {
        this.homeTeamId = homeTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.home_team
     *
     * @return the value of jrs_match_videotape.home_team
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getHomeTeam() {
        return homeTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.home_team
     *
     * @param homeTeam the value for jrs_match_videotape.home_team
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setHomeTeam(String homeTeam) {
        this.homeTeam = homeTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.home_team_log
     *
     * @return the value of jrs_match_videotape.home_team_log
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getHomeTeamLog() {
        return homeTeamLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.home_team_log
     *
     * @param homeTeamLog the value for jrs_match_videotape.home_team_log
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setHomeTeamLog(String homeTeamLog) {
        this.homeTeamLog = homeTeamLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.off_team_id
     *
     * @return the value of jrs_match_videotape.off_team_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getOffTeamId() {
        return offTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.off_team_id
     *
     * @param offTeamId the value for jrs_match_videotape.off_team_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setOffTeamId(Integer offTeamId) {
        this.offTeamId = offTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.off_team
     *
     * @return the value of jrs_match_videotape.off_team
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getOffTeam() {
        return offTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.off_team
     *
     * @param offTeam the value for jrs_match_videotape.off_team
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setOffTeam(String offTeam) {
        this.offTeam = offTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.off_team_log
     *
     * @return the value of jrs_match_videotape.off_team_log
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getOffTeamLog() {
        return offTeamLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.off_team_log
     *
     * @param offTeamLog the value for jrs_match_videotape.off_team_log
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setOffTeamLog(String offTeamLog) {
        this.offTeamLog = offTeamLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.score
     *
     * @return the value of jrs_match_videotape.score
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.score
     *
     * @param score the value for jrs_match_videotape.score
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setScore(String score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.match_time
     *
     * @return the value of jrs_match_videotape.match_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getMatchTime() {
        return matchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.match_time
     *
     * @param matchTime the value for jrs_match_videotape.match_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setMatchTime(String matchTime) {
        this.matchTime = matchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.delete_status
     *
     * @return the value of jrs_match_videotape.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.delete_status
     *
     * @param deleteStatus the value for jrs_match_videotape.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.create_user_id
     *
     * @return the value of jrs_match_videotape.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.create_user_id
     *
     * @param createUserId the value for jrs_match_videotape.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.create_time
     *
     * @return the value of jrs_match_videotape.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.create_time
     *
     * @param createTime the value for jrs_match_videotape.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.modifiy_user_id
     *
     * @return the value of jrs_match_videotape.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getModifiyUserId() {
        return modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.modifiy_user_id
     *
     * @param modifiyUserId the value for jrs_match_videotape.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setModifiyUserId(Integer modifiyUserId) {
        this.modifiyUserId = modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_match_videotape.modifiy_time
     *
     * @return the value of jrs_match_videotape.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getModifiyTime() {
        return modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_match_videotape.modifiy_time
     *
     * @param modifiyTime the value for jrs_match_videotape.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setModifiyTime(Date modifiyTime) {
        this.modifiyTime = modifiyTime;
    }
}