package com.jrs.www.po;

public class JrsMobileAdvPositionType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv_position_type.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_mobile_adv_position_type.adv_position_type
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    private String advPositionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv_position_type.id
     *
     * @return the value of jrs_mobile_adv_position_type.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv_position_type.id
     *
     * @param id the value for jrs_mobile_adv_position_type.id
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_mobile_adv_position_type.adv_position_type
     *
     * @return the value of jrs_mobile_adv_position_type.adv_position_type
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public String getAdvPositionType() {
        return advPositionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_mobile_adv_position_type.adv_position_type
     *
     * @param advPositionType the value for jrs_mobile_adv_position_type.adv_position_type
     *
     * @mbg.generated Tue Jun 05 17:24:15 GMT+08:00 2018
     */
    public void setAdvPositionType(String advPositionType) {
        this.advPositionType = advPositionType;
    }
}