package com.jrs.www.po;

import java.util.Date;

public class JrsPcAdv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.pc_adv_position_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer pcAdvPositionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.adv_img
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String advImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.show_start_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date showStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.show_end_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date showEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.jump_url
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String jumpUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer modifiyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date modifiyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.id
     *
     * @return the value of jrs_pc_adv.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.id
     *
     * @param id the value for jrs_pc_adv.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.pc_adv_position_id
     *
     * @return the value of jrs_pc_adv.pc_adv_position_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getPcAdvPositionId() {
        return pcAdvPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.pc_adv_position_id
     *
     * @param pcAdvPositionId the value for jrs_pc_adv.pc_adv_position_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setPcAdvPositionId(Integer pcAdvPositionId) {
        this.pcAdvPositionId = pcAdvPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.adv_img
     *
     * @return the value of jrs_pc_adv.adv_img
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getAdvImg() {
        return advImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.adv_img
     *
     * @param advImg the value for jrs_pc_adv.adv_img
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setAdvImg(String advImg) {
        this.advImg = advImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.show_start_time
     *
     * @return the value of jrs_pc_adv.show_start_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getShowStartTime() {
        return showStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.show_start_time
     *
     * @param showStartTime the value for jrs_pc_adv.show_start_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setShowStartTime(Date showStartTime) {
        this.showStartTime = showStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.show_end_time
     *
     * @return the value of jrs_pc_adv.show_end_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getShowEndTime() {
        return showEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.show_end_time
     *
     * @param showEndTime the value for jrs_pc_adv.show_end_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setShowEndTime(Date showEndTime) {
        this.showEndTime = showEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.jump_url
     *
     * @return the value of jrs_pc_adv.jump_url
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getJumpUrl() {
        return jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.jump_url
     *
     * @param jumpUrl the value for jrs_pc_adv.jump_url
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.delete_status
     *
     * @return the value of jrs_pc_adv.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.delete_status
     *
     * @param deleteStatus the value for jrs_pc_adv.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.create_user_id
     *
     * @return the value of jrs_pc_adv.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.create_user_id
     *
     * @param createUserId the value for jrs_pc_adv.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.create_time
     *
     * @return the value of jrs_pc_adv.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.create_time
     *
     * @param createTime the value for jrs_pc_adv.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.modifiy_user_id
     *
     * @return the value of jrs_pc_adv.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getModifiyUserId() {
        return modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.modifiy_user_id
     *
     * @param modifiyUserId the value for jrs_pc_adv.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setModifiyUserId(Integer modifiyUserId) {
        this.modifiyUserId = modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv.modifiy_time
     *
     * @return the value of jrs_pc_adv.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getModifiyTime() {
        return modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv.modifiy_time
     *
     * @param modifiyTime the value for jrs_pc_adv.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setModifiyTime(Date modifiyTime) {
        this.modifiyTime = modifiyTime;
    }
}