package com.jrs.www.po;

import java.util.Date;

public class JrsPcAdvPosition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv_position.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv_position.position
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv_position.position_explain
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String positionExplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv_position.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv_position.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv_position.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv_position.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Integer modifiyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrs_pc_adv_position.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    private Date modifiyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv_position.id
     *
     * @return the value of jrs_pc_adv_position.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv_position.id
     *
     * @param id the value for jrs_pc_adv_position.id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv_position.position
     *
     * @return the value of jrs_pc_adv_position.position
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv_position.position
     *
     * @param position the value for jrs_pc_adv_position.position
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv_position.position_explain
     *
     * @return the value of jrs_pc_adv_position.position_explain
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getPositionExplain() {
        return positionExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv_position.position_explain
     *
     * @param positionExplain the value for jrs_pc_adv_position.position_explain
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setPositionExplain(String positionExplain) {
        this.positionExplain = positionExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv_position.delete_status
     *
     * @return the value of jrs_pc_adv_position.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv_position.delete_status
     *
     * @param deleteStatus the value for jrs_pc_adv_position.delete_status
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv_position.create_user_id
     *
     * @return the value of jrs_pc_adv_position.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv_position.create_user_id
     *
     * @param createUserId the value for jrs_pc_adv_position.create_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv_position.create_time
     *
     * @return the value of jrs_pc_adv_position.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv_position.create_time
     *
     * @param createTime the value for jrs_pc_adv_position.create_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv_position.modifiy_user_id
     *
     * @return the value of jrs_pc_adv_position.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Integer getModifiyUserId() {
        return modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv_position.modifiy_user_id
     *
     * @param modifiyUserId the value for jrs_pc_adv_position.modifiy_user_id
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setModifiyUserId(Integer modifiyUserId) {
        this.modifiyUserId = modifiyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrs_pc_adv_position.modifiy_time
     *
     * @return the value of jrs_pc_adv_position.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public Date getModifiyTime() {
        return modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrs_pc_adv_position.modifiy_time
     *
     * @param modifiyTime the value for jrs_pc_adv_position.modifiy_time
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    public void setModifiyTime(Date modifiyTime) {
        this.modifiyTime = modifiyTime;
    }
}