package com.jrs.www.dao;

import com.jrs.www.po.JrsAdmin;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface JrsAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_admin
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_admin
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_admin
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_admin
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsAdmin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_admin
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsAdmin record);

    List<JrsAdmin> selectByJrsAdmin(JrsAdmin record);
}