package com.jrs.www.dao;

import com.jrs.www.po.JrsMobileSys;
import java.util.List;

public interface JrsMobileSysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_sys
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_sys
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsMobileSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_sys
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsMobileSys selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_sys
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsMobileSys> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_sys
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsMobileSys record);
}