package com.jrs.www.dao;

import com.jrs.www.po.JrsMatchVideotape;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface JrsMatchVideotapeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_videotape
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_videotape
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsMatchVideotape record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_videotape
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsMatchVideotape selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_videotape
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsMatchVideotape> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_videotape
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsMatchVideotape record);

    void insertList(List<JrsMatchVideotape> recordList);

    List<JrsMatchVideotape> selectAllByType(Integer matchTypeId);
}