package com.jrs.www.dao;

import com.jrs.www.po.JrsMatchVideotapeUrl;
import java.util.List;

public interface JrsMatchVideotapeUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_videotape_url
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsMatchVideotapeUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_videotape_url
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsMatchVideotapeUrl> selectAll();
}