package com.jrs.www.dao;

import com.jrs.www.po.JrsMobileAdvPositionType;
import java.util.List;

public interface JrsMobileAdvPositionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_adv_position_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_adv_position_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsMobileAdvPositionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_adv_position_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsMobileAdvPositionType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_adv_position_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsMobileAdvPositionType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_mobile_adv_position_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsMobileAdvPositionType record);
}