package com.jrs.www.dao;

import com.jrs.www.po.JrsMatchType;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface JrsMatchTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsMatchType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsMatchType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsMatchType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_match_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsMatchType record);
}