package com.jrs.www.dao;

import com.jrs.www.po.JrsPlayEnvironment;
import java.util.List;

public interface JrsPlayEnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_environment
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_environment
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsPlayEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_environment
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsPlayEnvironment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_environment
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsPlayEnvironment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_environment
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsPlayEnvironment record);
}