package com.jrs.www.dao;

import com.jrs.www.po.JrsPcAdvPosition;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface JrsPcAdvPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_pc_adv_position
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    int insert(JrsPcAdvPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_pc_adv_position
     *
     * @mbg.generated Mon Jun 04 17:56:27 GMT+08:00 2018
     */
    List<JrsPcAdvPosition> selectAll();
}