package com.jrs.www.dao;

import com.jrs.www.po.JrsPlayType;
import java.util.List;

public interface JrsPlayTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsPlayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsPlayType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsPlayType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_play_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsPlayType record);
}