package com.jrs.www.dao;

import com.jrs.www.po.JrsPcAdv;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface JrsPcAdvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_pc_adv
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_pc_adv
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsPcAdv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_pc_adv
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsPcAdv selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_pc_adv
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsPcAdv> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_pc_adv
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsPcAdv record);

    List<JrsPcAdv> selectAllByPositionId(Integer positionId);
}