package com.jrs.www.dao;

import com.jrs.www.po.JrsVideoStreamType;
import java.util.List;

public interface JrsVideoStreamTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_video_stream_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_video_stream_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int insert(JrsVideoStreamType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_video_stream_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    JrsVideoStreamType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_video_stream_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    List<JrsVideoStreamType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jrs_video_stream_type
     *
     * @mbg.generated Fri Jun 01 16:07:07 GMT+08:00 2018
     */
    int updateByPrimaryKey(JrsVideoStreamType record);
}